### ISSUE TITLE
seleccion de tanque

### ISSUE THREAD

**Issue by cataxel** [cataxel/ProyectoTanque#4]
buscar y seleccionar un tanque a usar en el proyecto

**Comment by mruvalcaba02** [comment]
El tanque esta dividido en 2 partes una seria la parte del carrito y otra la parte de la torreta, anexo imágenes del diseño del tanque seleccionado.

![Image](https://github.com/cataxel/ProyectoTanque/assets/166536344/1806b1cd-61af-4c1a-975e-e996d0bf5cc8)
![Image](https://github.com/cataxel/ProyectoTanque/assets/166536344/949ee461-7c85-42ab-9550-2ee0b55b0107)
